<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Database.LiteDb</PackageId>
    <Version>1.0.0</Version>
    <Authors>Dio Liew</Authors>
    <Description>A LiteDb databse package wrapper.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/DioLiew/Database/tree/main/Database.LiteDb</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="CSharpExt.Core" Version="1.0.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
  </ItemGroup>
</Project>
